name: dynamic_tab
description: "Flutter package for creating dynamic tabs."
version: 1.0.0
homepage: https://github.com/alihaider78222/dynamic_tab
issue_tracker: https://github.com/alihaider78222/dynamic_tab/issues

environment:
  sdk: '>=3.2.1 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:


